### ISSUE TITLE
Cannot compile 无法编译

### ISSUE THREAD

**Issue by HongchengQ** [issueMel/Go-Grasscutter#5]
我使用win系统 go语言版本为1.22.3 在使用go build Go-Grasscutter后报错
I am using Windows with Go language version 1.22.3. I encountered an error when using go build for Go-Grasscutter.

    PS C:\Users\xxxx\Documents\GitHub\Go-Grasscutter> go build Go-Grasscutter
    go: downloading github.com/jinzhu/copier v0.4.0
    # Go-Grasscutter/server/kcp/session
    server\kcp\session\management.go:19:28: undefined: config.Conf
    # Go-Grasscutter/server/http/handler
    server\http\handler\region.go:39:14: undefined: config.Conf
    server\http\handler\region.go:51:11: undefined: config.LrString
    server\http\handler\region.go:53:24: undefined: config.LrInt
    server\http\handler\region.go:68:18: undefined: config.LrString
    server\http\handler\region.go:69:18: undefined: config.LrInt

随后我查看了源代码 发现在 config\config.go 中删除 import "C" 这一行内容即可通过编译
Then I checked the source code and found that deleting the line import 'C' in config\config.go allowed the compilation to succeed.

**Comment by issueMel** [comment]
感谢pr，我双端都启用cgo，所以一直没注意到这个问题。
如果没有任何问题的话， 请关闭该issue。
